## Definicion de la solicitud de almacenamiento persistente para la bbdd en mongodb
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi