## Variables de entorno sensibles codificadas en Base64 para la seguridad en kubernetes (MONGO_URL, JWT_SECRET)
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
data:
  MONGO_URL: bW9uZ29kYitzcnY6Ly9tYXNzZXZpbGxhbGJhOkNlcnNlaTIwMjQhQGNsdXN0ZXJ2aWxsYWxiYS5jb2NxaC5tb25nb2RiLm5ldC9iZTNzaG9wP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  JWT_SECRET: dHVfc3VwZXJfc2VjcmV0b19qd3Q=
