## Variables de entorno sensibles codificadas en Base64 para la seguridad en kubernetes (MONGO_URL, JWT_SECRET)
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
type: Opaque
data:
  MONGO_URL: bW9uZ29kYjovL21vbmdvLXNlcnZpY2U6MjcwMTcvYmUzc2hvcA==
  JWT_SECRET: dHVfc3VwZXJfc2VjcmV0b19qd3Q=
